# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

remote_theme: "mmistakes/minimal-mistakes@4.26.2"

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Stefan Radman

email: sradman@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the personal website of Stefan Radman, Ph.D.
github_username: virmodoetiae
minimal_mistakes_skin: dark
baseurl: ""

logo: "/assets/images/favicon/android-chrome-192x192.png"

search: false

locale: "en-US"

sass:
  style: compressed

# Build settings
markdown: kramdown
kramdown:
  hard_wrap: true

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Belgrade # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name     : "Stefan Radman, Ph.D."
  avatar   : "/assets/images/profile_0.jpeg"
  bio      : "Serbian-Italian nuclear engineer and scientific programmer"
  location : "Lugano, Switzerland"
  email    : "sradman@protonmail.com"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/stefan-radman-073154b4/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/virmodoetiae"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google-scholar"
      url: "https://scholar.google.com/citations?user=viEDzQUAAAAJ"

footer:
  email : "sradman@protonmail.com"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/stefan-radman-073154b4/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/virmodoetiae"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google-scholar"
      url: "https://scholar.google.com/citations?user=viEDzQUAAAAJ"
  

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

atom_feed:
  hide: true
